import json, pathlib

DB_PATH = pathlib.Path(__file__).parent.parent / "data" / "artwork_era_db.json"
db = json.loads(DB_PATH.read_text(encoding="utf-8"))
existing = {a["artwork_id"] for a in db["artworks"]}

NEW = [
  {"artwork_id":"the_fifer","title":"The Fifer","title_aliases":["fifer","le fifre","피리 부는 소년","피리부는소년"],"artist":"Édouard Manet","art_movement":"사실주의 / 인상주의 전환기","creation_period":"1866년 제작. 황제 근위대 소속으로 보이는 어린 고수(鼓手)를 모델로 했습니다. 살롱에 출품했으나 낙선했으며, 에밀 졸라는 이 작품을 극찬했습니다. 현재 파리 오르세 미술관 소장.","historical_context":"1860년대 프랑스 제2제정 시기, 살롱 심사위원들은 여전히 역사화를 최상위로 여겼고 마네처럼 현실 인물을 대담하게 그린 화가들은 낙선과 논란을 반복했습니다. 1863년 낙선전이 아카데미 권위에 대한 저항의 출발점이었습니다.","artist_context":"마네는 전통 원근법과 명암법을 파격적으로 단순화하고 평면적 색면을 대담하게 사용하면서 인상주의 세대에게 결정적 영향을 미쳤습니다. 스페인 여행에서 받은 벨라스케스의 영향이 이 작품에 강하게 드러납니다.","visual_connection":"회색 중간톤 없이 밝은 색면이 직접 맞붙는 평면적 구성은 일본 우키요에의 영향을 보여줍니다. 배경을 거의 지우고 인물만 클로즈업하는 방식은 당시 원근법 전통을 정면으로 부정합니다. 빨간 바지·파란 재킷·흰 앞섶의 삼색 대비는 강렬하면서도 절제되어 있으며, 소년의 담담한 표정이 인상적입니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"a_bar_at_the_folies_bergere","title":"A Bar at the Folies-Bergère","title_aliases":["folies bergere","폴리베르제르의 술집","bar at the folies"],"artist":"Édouard Manet","art_movement":"인상주의","creation_period":"1882년, 마네가 세상을 떠나기 1년 전 제작한 마지막 대작. 파리 유흥 공연장 폴리베르제르의 바텐더 쉬종을 모델로 했으며, 거울 속 반영이 화면 전체를 차지합니다.","historical_context":"19세기 말 파리 벨 에포크 시대, 폴리베르제르는 서커스·음악·곡예가 공존하는 대중 공연장이었습니다.","artist_context":"운동실조증을 앓으며 죽음을 앞두고 있던 마네가 지팡이를 짚으며 완성한 작품입니다. 거울 속 반영이 실제 공간과 맞지 않는 왜곡은 의도적 장치입니다.","visual_connection":"바텐더의 공허한 눈빛과 화려한 유흥가 배경의 대비는 현대인의 고독을 포착합니다. 거울 속 반영의 어긋남은 관람자까지 그림 속 공간으로 끌어들입니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"portrait_of_dr_gachet","title":"Portrait of Dr. Gachet","title_aliases":["dr gachet","가셰 박사의 초상","doctor gachet"],"artist":"Vincent van Gogh","art_movement":"후기 인상주의","creation_period":"1890년 6월, 반 고흐가 생레미 퇴원 직후 오베르쉬르우아즈에서 제작. 그를 치료하던 폴 가셰 의사를 모델로 했으며 반 고흐는 현시대의 슬픈 표정을 담았다고 썼습니다. 1990년 경매에서 당시 최고가 8,250만 달러에 낙찰되었습니다.","historical_context":"19세기 말 유럽에서 정신 질환에 대한 의학적 관심이 높아지던 시기였습니다. 가셰 박사는 인상주의 화가들과 교류하던 아마추어 화가이자 의사였습니다.","artist_context":"생레미 퇴원 후 고흐는 오베르에서 극도로 생산적이었지만 내면의 혼란도 컸습니다. 이 초상화를 그린 지 두 달 뒤 세상을 떠났습니다.","visual_connection":"우울해 보이는 눈빛과 뺨에 괸 손, 테이블 위 폭스글러브 식물이 슬픔과 치유의 복잡한 감정을 동시에 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_sower","title":"The Sower","title_aliases":["sower","le semeur","씨 뿌리는 사람","씨뿌리는"],"artist":"Vincent van Gogh","art_movement":"후기 인상주의","creation_period":"1888년 아를에서 제작. 반 고흐가 존경했던 밀레의 동명 작품에서 영감을 받았습니다.","historical_context":"19세기 후반 농업 노동에 대한 낭만적 시각이 예술계에 확산되었습니다.","artist_context":"반 고흐에게 씨 뿌리는 자는 희망과 부활의 상징이었습니다. 수확과 씨앗 모티프를 반복해 사용하며 삶의 순환에 강한 매력을 느꼈습니다.","visual_connection":"거대한 태양이 지는 방향으로 농부가 걸어가는 구도는 인간과 자연의 조화를 역동적으로 표현합니다. 노란색과 보라색의 보색 대비가 강렬한 에너지를 부여합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"cypresses","title":"Cypresses","title_aliases":["cypress","사이프러스 나무","les cypres","측백나무"],"artist":"Vincent van Gogh","art_movement":"후기 인상주의","creation_period":"1889년 생레미 정신병원 입원 중 제작. 반 고흐는 사이프러스 나무를 이집트 오벨리스크처럼 아름답다고 편지에 썼습니다.","historical_context":"사이프러스는 지중해 지역에서 전통적으로 묘지와 죽음을 상징하는 나무입니다. 반 고흐는 이 상징성을 생명력의 표현으로 전환했습니다.","artist_context":"병원 입원 중 창문 너머 보이는 사이프러스 나무들을 반복해서 그렸습니다. 해바라기를 다루듯 사이프러스 연작을 구상했습니다.","visual_connection":"하늘을 향해 불꽃처럼 솟아오르는 나무의 형태와 소용돌이치는 하늘이 합쳐져 내면의 격동을 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"olive_trees","title":"Olive Trees","title_aliases":["olive tree","올리브 나무","oliviers"],"artist":"Vincent van Gogh","art_movement":"후기 인상주의","creation_period":"1889년 생레미 정신병원 정원에서 반복해 그린 연작.","historical_context":"남프랑스 프로방스의 올리브 나무는 수백 년을 사는 고목으로 지역 문화의 상징입니다.","artist_context":"반 고흐는 올리브 수확을 성경적 주제로 연결하며 직접 관찰한 나무를 통해 종교적 감성을 표현하려 했습니다.","visual_connection":"비틀린 나무 줄기와 역동적 붓터치가 생명력과 고통을 동시에 담아냅니다. 은빛 초록 잎과 따뜻한 토색 대지가 조화를 이룹니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"postman_roulin","title":"Portrait of the Postman Roulin","title_aliases":["postman roulin","roulin","우편배달부 룰랭"],"artist":"Vincent van Gogh","art_movement":"후기 인상주의","creation_period":"1888년 아를에서 제작. 반 고흐의 가장 친한 친구였던 우편배달부 조제프 룰랭과 그 가족의 초상화를 여러 점 남겼습니다.","historical_context":"반 고흐는 아를에서 고독하게 지내며 룰랭 가족을 유일한 사교 관계로 삼았습니다.","artist_context":"룰랭은 반 고흐의 귀 절단 사건 이후 곁에서 돌봐준 인물입니다. 그를 아버지처럼 생긴 선한 사람이라 불렀습니다.","visual_connection":"짙은 청색 제복과 금빛 단추, 무성한 수염이 강렬한 인상을 남깁니다. 배경의 꽃 문양이 인물의 따뜻한 품성을 암시합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"poppy_field","title":"Poppy Field","title_aliases":["poppies","양귀비 밭","les coquelicots"],"artist":"Claude Monet","art_movement":"인상주의","creation_period":"1873년, 모네가 아르장퇴유에 정착한 직후 제작. 아내 카미유와 아들 장이 등장합니다.","historical_context":"1870년대 파리 근교 아르장퇴유는 산업화와 자연이 공존하던 신흥 주거지였습니다.","artist_context":"모네는 야외에서 빠르게 그리는 앙플레르 방식을 실천했습니다. 양귀비 연작은 빛과 색채의 순간적 인상을 포착한 대표작입니다.","visual_connection":"붉은 양귀비꽃이 물결치는 초록 들판과 흰 구름 사이 파란 하늘이 상쾌한 여름날의 감각을 그대로 전달합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"rouen_cathedral","title":"Rouen Cathedral, West Facade","title_aliases":["rouen cathedral","루앙 대성당","cathedrale de rouen"],"artist":"Claude Monet","art_movement":"인상주의","creation_period":"1892~1894년, 모네가 루앙 대성당 맞은편 상점을 빌려 다른 시간대와 날씨에 30점 이상 반복해 그렸습니다.","historical_context":"19세기 말 프랑스에서 빛과 분위기의 변화를 기록하는 연작 방식이 유행했습니다.","artist_context":"모네는 같은 대상이 빛의 조건에 따라 완전히 다른 모습으로 보인다는 것을 연작으로 증명했습니다. 아침·정오·저녁·안개 속 각각 다른 캔버스를 동시에 작업했습니다.","visual_connection":"두꺼운 임파스토로 쌓인 돌의 질감이 빛에 따라 금빛·장밋빛·회청색으로 변하며 건물이 아니라 빛 자체가 주제임을 보여줍니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_umbrellas","title":"The Umbrellas","title_aliases":["umbrellas","우산들","les parapluies"],"artist":"Pierre-Auguste Renoir","art_movement":"인상주의","creation_period":"1881~1886년에 걸쳐 제작. 르누아르의 화풍 변화가 한 화면에 담긴 독특한 작품으로 오른쪽은 초기 인상주의, 왼쪽은 후기 고전주의 방식으로 그려져 있습니다.","historical_context":"19세기 후반 파리에 우산이 대중화되면서 도시 중산층의 야외 생활이 활발해졌습니다.","artist_context":"르누아르는 1881년 이탈리아 여행 후 라파엘로 영향을 받아 선묘 중심의 고전적 방식으로 전환했습니다.","visual_connection":"우산들이 만드는 원형 리듬과 비오는 날 파리 거리의 생동감이 도시 서정을 포착합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"two_sisters","title":"Two Sisters","title_aliases":["on the terrace","테라스에서","두자매"],"artist":"Pierre-Auguste Renoir","art_movement":"인상주의","creation_period":"1881년 제작. 시카고 아트 인스티튜트 소장. 실제 자매가 아닌 두 모델을 기용했습니다.","historical_context":"19세기 후반 인상주의 화가들은 부르주아 여성의 일상을 즐겨 그렸습니다.","artist_context":"르누아르는 화사한 색채와 부드러운 붓터치로 행복한 일상을 포착하는 것을 특기로 삼았습니다.","visual_connection":"꽃장식 모자와 밝은 색의 의상, 뒤편 센강의 햇살이 어우러져 인상주의 특유의 밝고 화사한 분위기를 자아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"virgin_of_the_rocks","title":"Virgin of the Rocks","title_aliases":["virgin of the rocks","암굴의 성모","vierge aux rochers"],"artist":"Leonardo da Vinci","art_movement":"르네상스","creation_period":"1483~1486년 루브르 버전, 1495~1508년 런던 내셔널갤러리 버전 두 점이 존재합니다. 밀라노 성 프란체스코 교회 제단화로 의뢰받았습니다.","historical_context":"15세기 밀라노는 스포르차 가문의 후원 아래 예술이 번성했습니다.","artist_context":"다 빈치는 이 작품에서 스푸마토 기법을 완성에 가깝게 구현했습니다. 암굴이라는 신비로운 자연 배경은 그의 지질학적 관심을 반영합니다.","visual_connection":"어두운 암굴 속에서 성모·아기 예수·요한·천사가 피라미드 구도를 이루며, 스푸마토로 처리된 안개 같은 배경이 성스러운 분위기를 자아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"vitruvian_man","title":"Vitruvian Man","title_aliases":["vitruvian man","비트루비우스 인체도","uomo vitruviano"],"artist":"Leonardo da Vinci","art_movement":"르네상스","creation_period":"1490년경, 다 빈치가 로마 건축가 비트루비우스의 인체 비례론을 직접 해석해 그린 스케치. 원과 정사각형에 동시에 내접하는 인체를 표현했습니다.","historical_context":"르네상스 인문주의는 고대 그리스·로마의 이상적 인체 비례를 재발견했습니다.","artist_context":"다 빈치의 해부학 연구는 인체를 우주적 조화의 중심으로 보는 르네상스 사상을 명확하게 시각화했습니다.","visual_connection":"두 자세가 겹쳐진 인체가 원과 사각형에 동시에 맞아떨어지는 기하학적 질서는 인간이 자연의 황금 비례 그 자체임을 선언합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_last_judgment","title":"The Last Judgment","title_aliases":["last judgment","최후의 심판","giudizio universale"],"artist":"Michelangelo","art_movement":"르네상스 / 매너리즘","creation_period":"1536~1541년, 교황 바오로 3세의 의뢰로 시스티나 예배당 제단 벽화로 제작. 미켈란젤로가 60세를 넘긴 나이에 완성한 만년의 대작입니다.","historical_context":"1527년 로마 약탈과 종교개혁의 충격으로 가톨릭 교회는 위기 의식에 빠졌습니다. 최후의 심판은 이 불안을 반영한 경고의 메시지를 담고 있습니다.","artist_context":"미켈란젤로는 이상화된 고전 인체 대신 고통과 긴장으로 뒤틀린 인체를 표현하며 매너리즘으로 이행했습니다.","visual_connection":"400여 명의 인물이 소용돌이치는 구도 속에 예수 그리스도를 중심으로 천국과 지옥으로 나뉘는 장면이 압도적 스케일로 펼쳐집니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"david","title":"David","title_aliases":["david statue","다비드 상","davide"],"artist":"Michelangelo","art_movement":"르네상스","creation_period":"1501~1504년, 미켈란젤로가 26~29세에 완성. 피렌체 시뇨리아 광장에 설치되었으며 현재는 아카데미아 미술관 소장.","historical_context":"피렌체 공화국은 메디치 가문 추방 후 외부 위협에 맞서는 시민 공화국의 상징이 필요했습니다.","artist_context":"미켈란젤로는 골리앗과 싸우기 직전 긴장한 순간을 포착했습니다. 고대 그리스 조각의 이상미를 완벽하게 재현하면서도 심리적 표현을 더했습니다.","visual_connection":"4.34미터 대리석 인체가 뿜어내는 긴장감—물매를 쥔 손, 굳은 눈빛, 팽팽한 근육—은 전투 직전 정신 집중의 순간을 영원화합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"pieta","title":"Pietà","title_aliases":["pieta","피에타","lamentation"],"artist":"Michelangelo","art_movement":"르네상스","creation_period":"1498~1499년, 미켈란젤로가 23세에 완성. 현재 성 베드로 대성당 소장.","historical_context":"15세기 말 이탈리아는 전쟁과 흑사병으로 죽음에 대한 성찰이 깊었습니다.","artist_context":"완성 후 사람들이 다른 작가 작품으로 알자 미켈란젤로가 직접 성모의 띠에 자신의 이름을 새겼습니다. 유일하게 서명한 작품입니다.","visual_connection":"23세 청년이 조각한 성모 마리아의 얼굴은 실제보다 젊게 표현되었습니다. 미켈란젤로는 성모의 영원한 순수함을 표현하기 위해서라고 설명했습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"sistine_madonna","title":"Sistine Madonna","title_aliases":["sistine madonna","시스티나 성모","성모","madonna sistina"],"artist":"Raphael","art_movement":"르네상스","creation_period":"1512년, 교황 율리오 2세의 의뢰로 제작. 독일 드레스덴 미술관 소장. 하단의 두 천사 이미지가 현대에 독립적으로 유명해졌습니다.","historical_context":"16세기 초 바티칸은 대규모 예술 사업을 진행했으며, 라파엘로는 미켈란젤로·다 빈치와 함께 르네상스 3대 거장으로 활약했습니다.","artist_context":"라파엘로는 이상적 아름다움과 조화를 추구했습니다. 성모 마리아의 친근하면서도 신성한 표현이 특징입니다.","visual_connection":"구름 위에 서 있는 성모와 아기 예수, 양쪽의 성 식스토와 성 바르바라, 하단의 두 천사가 완벽한 삼각 구도를 이룹니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"view_of_delft","title":"View of Delft","title_aliases":["view of delft","delft","델프트"],"artist":"Johannes Vermeer","art_movement":"바로크 / 황금시대","creation_period":"1660~1661년경 제작. 헤이그 마우리츠하이스 미술관 소장. 마르셀 프루스트가 세상에서 가장 아름다운 그림이라 극찬했습니다.","historical_context":"17세기 네덜란드 황금시대, 델프트는 도자기 산업과 무역으로 번성한 도시였습니다.","artist_context":"베르메르는 평생 델프트를 거의 떠나지 않았습니다. 카메라 옵스쿠라를 활용해 빛의 정밀한 묘사를 구현했다는 설이 있습니다.","visual_connection":"수면에 반영된 도시, 구름이 드리운 하늘, 건물에 내리쬐는 빛의 미묘한 변화가 도시 풍경을 서정적으로 담아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"return_of_the_prodigal_son","title":"The Return of the Prodigal Son","title_aliases":["prodigal son","탕자","return prodigal"],"artist":"Rembrandt van Rijn","art_movement":"바로크","creation_period":"1668~1669년경, 렘브란트의 마지막 작품 중 하나. 에르미타주 미술관 소장.","historical_context":"성경 누가복음의 탕자 비유는 용서와 귀환의 보편적 주제로 수많은 화가들이 그렸습니다.","artist_context":"아내·아들·재산을 모두 잃은 만년의 렘브란트가 그린 이 작품에는 개인적 고통과 용서에 대한 갈망이 담겨 있습니다.","visual_connection":"노인 아버지의 두 손이 아들의 어깨 위에 조심스럽게 얹히는 순간, 황금빛 빛이 두 인물을 감싸며 용서와 귀향의 감동을 극대화합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"rembrandt_self_portrait","title":"Self-Portrait at the Age of 34","title_aliases":["self portrait","자화상","rembrandt self portrait"],"artist":"Rembrandt van Rijn","art_movement":"바로크","creation_period":"1640년 제작. 런던 내셔널갤러리 소장. 렘브란트는 평생 90점 이상의 자화상을 남겼습니다.","historical_context":"17세기 네덜란드에서 자화상은 화가의 사회적 지위를 나타내는 중요한 수단이었습니다.","artist_context":"34세의 렘브란트는 당시 암스테르담에서 가장 성공한 화가였습니다. 라파엘로와 티치아노의 초상화를 의식한 귀족적 포즈를 취했습니다.","visual_connection":"키아로스쿠로(명암 대비) 기법으로 처리된 얼굴은 자부심과 내면의 깊이를 동시에 드러냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_broken_column","title":"The Broken Column","title_aliases":["broken column","부러진기둥","columna rota"],"artist":"Frida Kahlo","art_movement":"초현실주의 / 자전적 미술","creation_period":"1944년, 칼로가 척추 수술 후 의료 코르셋을 착용하며 제작.","historical_context":"칼로는 18세에 버스 사고로 척추를 크게 다쳤으며 평생 30회 이상 수술을 받았습니다.","artist_context":"부러진 이오니아식 기둥이 칼로의 척추를 대신하고, 몸 곳곳에 못이 박혀 있습니다. 신체적 고통을 그대로 시각화한 자전적 작품입니다.","visual_connection":"황량한 사막 배경 속에 혼자 서서 눈물을 참는 표정은 극한의 고통 속에서도 굴하지 않는 의지를 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"one_number_31","title":"One: Number 31","title_aliases":["number 31","no 31","넘버 31","action painting"],"artist":"Jackson Pollock","art_movement":"추상 표현주의","creation_period":"1950년 제작. 뉴욕 현대미술관(MoMA) 소장. 폴록의 드리핑 기법이 절정에 이른 작품입니다.","historical_context":"2차 세계대전 후 미국 뉴욕이 세계 미술의 중심으로 부상했으며 추상 표현주의가 미국 현대 미술을 대표하게 되었습니다.","artist_context":"폴록은 이젤을 버리고 캔버스를 바닥에 놓은 채 몸 전체를 움직여 물감을 흘리고 뿌리는 액션 페인팅을 개발했습니다.","visual_connection":"사방으로 뻗은 물감의 궤적은 화가의 몸 움직임 자체가 작품이 되는 과정을 보여줍니다. 혼돈처럼 보이지만 전체적으로 리드미컬한 균형이 있습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_great_wave","title":"The Great Wave off Kanagawa","title_aliases":["great wave","kanagawa","카나가와 해변의 높은 파도","파도","神奈川"],"artist":"Katsushika Hokusai","art_movement":"우키요에","creation_period":"1831년경, 호쿠사이의 연작 후가쿠 36경 중 가장 유명한 작품. 당시 70세가 넘은 노화가가 제작했습니다.","historical_context":"19세기 초 에도 시대 일본은 목판화 예술이 절정에 달했으며, 이후 이 작품은 유럽에 자포니즘 열풍을 일으켰습니다.","artist_context":"호쿠사이는 90세 생애 동안 30,000점 이상의 작품을 남겼습니다. 93세 임종 때 10년만 더 살면 진정한 화가가 될 것이라 했습니다.","visual_connection":"거대한 파도의 발톱 같은 끝과 그 너머 작게 보이는 후지산의 대비는 자연의 압도적 힘과 영원불변의 균형을 동시에 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"red_fuji","title":"Fine Wind, Clear Morning (Red Fuji)","title_aliases":["red fuji","붉은 후지산","gaifū kaisei","富嶽三十六景"],"artist":"Katsushika Hokusai","art_movement":"우키요에","creation_period":"1831년경, 후가쿠 36경 연작 중 가장 인기 있는 작품 중 하나.","historical_context":"후지산은 에도 시대 일본인에게 신성한 산으로 숭앙받았으며 무수한 예술 작품의 주제가 되었습니다.","artist_context":"호쿠사이는 후지산을 36개 다른 시각과 계절로 포착하려 했습니다. 붉은 후지는 새벽빛이 산을 붉게 물들이는 순간을 담았습니다.","visual_connection":"여름 아침 햇빛에 붉게 물든 후지산이 짙은 청색 하늘과 강렬한 대비를 이루며, 산 정상의 초록 덤불이 생동감을 더합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_garden_of_earthly_delights","title":"The Garden of Earthly Delights","title_aliases":["garden of earthly delights","세속적 쾌락의 동산","낙원","tuin der lusten"],"artist":"Hieronymus Bosch","art_movement":"북방 르네상스","creation_period":"1490~1510년경 제작. 스페인 마드리드 프라도 미술관 소장. 세 폭 제단화 형식으로 낙원·지상·지옥을 담았습니다.","historical_context":"중세 말~르네상스 초 네덜란드에서 도덕과 죄에 대한 종교적 성찰이 예술의 핵심 주제였습니다.","artist_context":"보스의 기괴한 상상력과 세밀한 묘사력은 당대 독보적이었습니다. 인간의 쾌락 추구와 그 결과를 풍자적으로 경고합니다.","visual_connection":"수백 명의 인물이 기괴한 생명체·식물·건물과 뒤섞인 화면은 인간 욕망의 백과사전처럼 펼쳐집니다. 세 폭을 합치면 창조에서 타락까지의 서사가 완성됩니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"nighthawks_hopper","title":"Nighthawks","title_aliases":["nighthawks","밤샘 손님들","야간 카페","밤의 카페"],"artist":"Edward Hopper","art_movement":"아메리칸 리얼리즘","creation_period":"1942년 제작. 시카고 아트 인스티튜트 소장. 진주만 공격 직후 제작되어 전쟁의 불안과 도시 고독을 담았다는 해석이 있습니다.","historical_context":"2차 세계대전 중 미국 사회에는 불안과 고독이 팽배했습니다. 도시화와 함께 익명성과 소외감이 새로운 사회 문제로 대두되었습니다.","artist_context":"호퍼는 빛과 그림자를 통해 현대 도시인의 고독을 포착하는 것을 평생의 주제로 삼았습니다.","visual_connection":"밤거리의 어둠 속에서 카페만 환하게 빛나고, 그 안의 인물들은 서로 가깝지만 각자의 고독 속에 있습니다. 창문 밖으로 보이는 빈 거리가 고독감을 증폭시킵니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"early_sunday_morning","title":"Early Sunday Morning","title_aliases":["early sunday morning","일요일 아침","이른 아침"],"artist":"Edward Hopper","art_movement":"아메리칸 리얼리즘","creation_period":"1930년 제작. 휘트니 미술관 소장.","historical_context":"대공황 직전의 미국, 도시화로 인한 익명성과 소외가 사회 현상이 되었습니다.","artist_context":"호퍼는 뉴욕 7번가 상점가를 모델로 했습니다. 텅 빈 거리와 이른 아침 햇빛의 조합이 특유의 고적함을 자아냅니다.","visual_connection":"아침 햇살이 상점 정면을 비추지만 창문 안은 어둡고 사람이 없습니다. 수평으로 길게 펼쳐진 화면이 고요한 일요일 아침의 적막을 강조합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"american_gothic","title":"American Gothic","title_aliases":["american gothic","아메리칸고딕"],"artist":"Grant Wood","art_movement":"아메리칸 리전주의","creation_period":"1930년 제작. 시카고 아트 인스티튜트 소장. 아이오와주 엘던의 고딕식 창문 달린 집에서 영감을 받았습니다.","historical_context":"대공황 시기 미국에서 도시 문화와 농촌 전통 사이의 긴장이 심해졌습니다. 우드는 미국 중서부 농촌 문화를 긍정적으로 재조명하려 했습니다.","artist_context":"우드의 여동생과 치과의사를 모델로 했습니다. 부녀 혹은 부부로 해석되며 농촌 미국의 엄숙한 근면함을 상징합니다.","visual_connection":"날카로운 세 갈래 쇠스랑과 두 인물의 굳은 표정, 수직으로 강조된 고딕 창문이 미국 농촌의 엄격한 도덕관을 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_dance","title":"The Dance","title_aliases":["the dance","dance","춤","la danse"],"artist":"Henri Matisse","art_movement":"야수주의","creation_period":"1910년 제작. 러시아 수집가 세르게이 슈추킨의 의뢰로 제작. 현재 에르미타주 미술관 소장.","historical_context":"20세기 초 유럽 아방가르드 예술은 아프리카·오세아니아 원시 미술에서 영감을 받아 형태를 단순화했습니다.","artist_context":"마티스는 색채를 통한 순수한 기쁨의 표현을 예술의 목표로 삼았습니다. 인체를 단순화한 선과 강렬한 원색으로 생명력을 표현했습니다.","visual_connection":"붉은 인체, 녹색 언덕, 파란 하늘—세 원색이 원을 이루며 춤추는 인물들과 함께 원초적 생명 에너지를 뿜어냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_two_fridas","title":"The Two Fridas","title_aliases":["two fridas","두 프리다","las dos fridas"],"artist":"Frida Kahlo","art_movement":"초현실주의 / 자전적 미술","creation_period":"1939년, 디에고 리베라와 이혼한 해에 제작. 멕시코 현대미술관 소장.","historical_context":"1930~40년대 멕시코에서 민족 정체성과 혼혈 문화(메스티소)에 대한 예술적 성찰이 활발했습니다.","artist_context":"유럽 혈통의 자아와 멕시코 원주민 혈통의 자아가 심장을 연결한 채 나란히 앉아 있습니다. 이혼 후의 고통과 정체성 갈등을 표현했습니다.","visual_connection":"두 프리다의 손이 잡고 있고 심장이 혈관으로 연결되어 있지만, 유럽풍 프리다의 심장은 절단되어 피를 흘립니다. 내면의 분열과 연결에 대한 갈망을 시각화합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"composition_viii","title":"Composition VIII","title_aliases":["composition viii","구성 8","composition 8"],"artist":"Wassily Kandinsky","art_movement":"추상주의 / 바우하우스","creation_period":"1923년 제작. 뉴욕 구겐하임 미술관 소장. 바우하우스 교수로 재직 중 기하학적 추상을 심화시킨 작품입니다.","historical_context":"1920년대 독일 바우하우스는 예술과 디자인의 통합을 추구했습니다. 기하학적 형태와 색채의 순수한 표현이 핵심 언어였습니다.","artist_context":"칸딘스키는 음악이 색채와 형태를 직접 연상시킨다는 이론을 개발했습니다. 그의 추상화는 색과 형태의 교향악입니다.","visual_connection":"원·삼각형·선이 상호 작용하며 시각적 리듬을 만들어냅니다. 각 형태와 색채 조합은 특정 감정 또는 음악적 음표를 연상시키도록 설계되었습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"composition_with_red_yellow_blue","title":"Composition with Red, Yellow and Blue","title_aliases":["composition red yellow blue","빨강 노랑 파랑","몬드리안"],"artist":"Piet Mondrian","art_movement":"신조형주의 / 데 스틸","creation_period":"1921년 제작. 몬드리안이 파리에서 데 스틸 그룹과 함께 순수 추상을 발전시키던 시기의 대표작.","historical_context":"1차 세계대전 후 유럽 예술가들은 순수한 조형 질서에서 이상적 평화를 찾으려 했습니다. 몬드리안의 신조형주의는 이 열망의 표현입니다.","artist_context":"몬드리안은 수직·수평선과 삼원색만을 사용해 우주의 본질적 질서를 표현하려 했습니다.","visual_connection":"검은 수직·수평선이 만드는 격자와 빨강·노랑·파랑·흰색의 배치는 단순하지만 완벽한 균형감을 줍니다. 현대 그래픽 디자인에 지대한 영향을 미쳤습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"broadway_boogie_woogie","title":"Broadway Boogie Woogie","title_aliases":["broadway boogie woogie","브로드웨이","부기우기"],"artist":"Piet Mondrian","art_movement":"신조형주의","creation_period":"1942~1943년, 뉴욕 망명 중 제작. MoMA 소장. 뉴욕 재즈와 도시 그리드에서 영감을 받아 초기 작품보다 훨씬 역동적입니다.","historical_context":"나치를 피해 뉴욕에 망명한 몬드리안은 재즈 음악과 뉴욕의 도시 에너지에 새로운 활력을 얻었습니다.","artist_context":"평생 굳어진 흑백 격자 스타일에서 벗어나 노란색 격자선과 색점들로 리드미컬한 도시 활기를 표현했습니다.","visual_connection":"노란 격자선 위의 빨강·파랑·노랑 점들이 재즈 리듬처럼 화면을 박자감 있게 채웁니다. 뉴욕 맨해튼의 도로망을 위에서 내려다본 것 같은 구도입니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"liberty_leading_the_people","title":"Liberty Leading the People","title_aliases":["liberty leading the people","자유의 여신","la liberté guidant le peuple","민중"],"artist":"Eugène Delacroix","art_movement":"낭만주의","creation_period":"1830년, 프랑스 7월 혁명을 기념해 제작. 루브르 박물관 소장.","historical_context":"1830년 7월 혁명으로 샤를 10세가 축출되고 루이 필리프가 즉위했습니다. 부르봉 왕정의 반동 정치에 맞선 시민 봉기였습니다.","artist_context":"들라크루아는 직접 혁명에 참여하지 않았지만 신문 삽화에서 영감을 받아 이 작품을 완성했습니다. 자유를 상징하는 여신을 현실적 시민들과 함께 그렸습니다.","visual_connection":"삼색기를 든 자유의 여신을 중심으로 다양한 계층의 시민들이 함께 전진하는 구도는 혁명의 열정과 연대를 역동적으로 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"where_do_we_come_from","title":"Where Do We Come From? What Are We? Where Are We Going?","title_aliases":["where do we come from","우리는 어디서 왔는가","고갱 대작"],"artist":"Paul Gauguin","art_movement":"후기 인상주의 / 상징주의","creation_period":"1897~1898년, 고갱이 타히티에서 제작. 보스턴 미술관 소장. 완성 후 자살을 시도했을 만큼 전력을 쏟은 작품입니다.","historical_context":"19세기 말 유럽 지식인들은 산업화와 물질주의에 환멸을 느끼며 원시적 순수함을 동경했습니다.","artist_context":"고갱은 문명을 등지고 타히티로 이주해 원시적 삶과 예술을 추구했습니다. 이 작품은 인간 존재의 근원적 질문을 담은 철학적 유언장입니다.","visual_connection":"오른쪽 갓 태어난 아이에서 왼쪽 노인까지 삶의 전 과정이 타히티 배경 속에 펼쳐집니다. 중앙의 과일을 따는 인물이 화면의 중심축을 이룹니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_raft_of_the_medusa","title":"The Raft of the Medusa","title_aliases":["raft of the medusa","메두사","le radeau de la méduse"],"artist":"Théodore Géricault","art_movement":"낭만주의","creation_period":"1818~1819년 제작. 루브르 박물관 소장. 1816년 실제 메두사호 난파 사건을 소재로 했습니다.","historical_context":"메두사호 난파 사건은 무능한 귀족 함장이 배를 침몰시키고 생존자들이 뗏목 위에서 기아와 살인을 경험한 충격적 사건으로 정치적 파장을 일으켰습니다.","artist_context":"제리코는 실제 생존자들을 인터뷰하고 시체를 직접 관찰하며 2년에 걸쳐 준비했습니다. 6×8미터의 대작으로 살롱을 충격에 빠뜨렸습니다.","visual_connection":"뗏목 위 생존자들이 지평선의 구조선을 향해 절망적으로 손을 뻗는 피라미드 구도는 희망과 절망의 극적 긴장을 최대화합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"napoleon_crossing_the_alps","title":"Napoleon Crossing the Alps","title_aliases":["napoleon alps","나폴레옹","알프스","napoleon crossing"],"artist":"Jacques-Louis David","art_movement":"신고전주의","creation_period":"1801~1805년 5점 제작. 나폴레옹의 의뢰로 그려진 정치 선전 작품입니다.","historical_context":"나폴레옹이 권력을 공고히 하던 시기, 영웅적 이미지 구축이 정치적으로 중요했습니다. 실제로는 노새를 타고 알프스를 넘었습니다.","artist_context":"다비드는 나폴레옹의 공식 화가였습니다. 역사적 사실보다 영웅적 이미지를 우선하는 정치적 회화의 전형입니다.","visual_connection":"역동적으로 앞발을 든 백마 위에서 손가락으로 전방을 가리키는 나폴레옹의 자세는 영웅주의와 지도력의 이상을 완벽하게 구현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"a_sunday_afternoon_grande_jatte","title":"A Sunday on La Grande Jatte","title_aliases":["grande jatte","la grande jatte","그랑자트","sunday afternoon"],"artist":"Georges Seurat","art_movement":"신인상주의 / 점묘주의","creation_period":"1884~1886년 제작. 시카고 아트 인스티튜트 소장. 작은 색 점들을 병치해 그리는 점묘법의 대표작입니다.","historical_context":"19세기 말 파리 근교 그랑자트 섬은 중산층의 주말 여가 공간이었습니다. 광학 이론을 예술에 적용하는 과학적 접근이 대두되었습니다.","artist_context":"쇠라는 색채 이론과 광학을 체계적으로 연구해 점묘법을 개발했습니다. 눈이 두 색의 점을 혼합해 새로운 색을 인식하는 원리를 활용했습니다.","visual_connection":"수백만 개의 작은 점들이 만들어내는 화면은 가까이서 보면 점들이, 멀리서 보면 조화로운 색면이 드러나는 이중 경험을 제공합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_blue_star","title":"The Star (L'Étoile)","title_aliases":["star","l etoile","발레리나","ballet star","별"],"artist":"Edgar Degas","art_movement":"인상주의","creation_period":"1878년경 제작. 파스텔 화. 파리 오르세 미술관 소장.","historical_context":"19세기 후반 파리 오페라는 부르주아 사교 공간이었으며 발레리나들은 가난한 배경에서 온 경우가 많았습니다.","artist_context":"드가는 파리 오페라의 무대 뒤와 연습실에 자유롭게 출입했습니다. 발레 댄서들의 움직임을 포착하는 것을 평생의 주제로 삼았습니다.","visual_connection":"스포트라이트 아래 혼자 조명받는 발레리나와 뒤편 어둠 속의 다른 인물들이 빛과 그림자로 무대의 순간을 포착합니다. 위에서 내려다보는 독특한 시점이 역동감을 더합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"blue_dancers","title":"Blue Dancers","title_aliases":["blue dancers","파란 무용수","danseuses bleues"],"artist":"Edgar Degas","art_movement":"인상주의","creation_period":"1897년경 제작. 파스텔 화. 모스크바 푸시킨 미술관 소장.","historical_context":"말년의 드가는 시력이 나빠지면서 유화보다 파스텔을 많이 사용했습니다.","artist_context":"드가는 만년에 시력이 크게 저하되면서도 발레리나 주제를 놓지 않았습니다. 형태보다 색채 효과에 집중하는 방향으로 변화했습니다.","visual_connection":"푸른 계열의 의상들이 화면 전체를 감싸며 차분하고 몽환적인 분위기를 자아냅니다. 인물들이 서로 겹치며 움직임과 정지의 순간을 동시에 담습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_card_players_cezanne","title":"The Card Players","title_aliases":["card players","les joueurs de cartes","카드 게임","카드놀이"],"artist":"Paul Cézanne","art_movement":"후기 인상주의","creation_period":"1890~1895년 5점 연작 제작. 프로방스 농부들을 모델로 했습니다.","historical_context":"19세기 후반 프랑스 농촌 일상이 예술의 주제로 부상했습니다.","artist_context":"세잔은 같은 주제를 반복하며 형태와 색채의 관계를 탐구했습니다. 큐비즘의 선구자로 평가받는 그의 기하학적 구성이 잘 드러납니다.","visual_connection":"마주 앉은 두 인물이 만드는 안정된 삼각 구도와 테이블의 수평선이 농촌 일상의 조용한 집중을 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"mont_sainte_victoire_cezanne","title":"Mont Sainte-Victoire","title_aliases":["mont sainte victoire","생트빅투아르","산"],"artist":"Paul Cézanne","art_movement":"후기 인상주의","creation_period":"1902~1906년 연작 제작. 세잔의 고향 프로방스의 생트빅투아르산을 60점 이상 반복해 그렸습니다.","historical_context":"19세기 말 인상주의 화가들이 풍경화를 혁신하던 시기, 세잔은 인상주의의 순간적 인상을 넘어 자연의 구조적 본질을 탐구했습니다.","artist_context":"세잔은 같은 산을 수십 년간 반복해 그리며 자연을 구·원기둥·원뿔 같은 기하학적 형태로 환원하는 방법론을 개발했습니다. 이는 큐비즘에 직접적 영향을 미쳤습니다.","visual_connection":"산과 들판, 나무들이 색채 면들로 분해되어 재구성되는 방식은 눈에 보이는 것을 넘어 자연의 구조적 질서를 드러내려는 시도입니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_rokeby_venus","title":"Rokeby Venus","title_aliases":["rokeby venus","비너스","venus del espejo","거울의 비너스"],"artist":"Diego Velázquez","art_movement":"바로크","creation_period":"1647~1651년경 제작. 런던 내셔널갤러리 소장. 스페인 황금시대에 남겨진 몇 안 되는 여성 나체화입니다.","historical_context":"17세기 스페인 가톨릭 문화에서 나체화는 종교적 이유로 금기시되었습니다. 벨라스케스는 예외적으로 이를 허용받았습니다.","artist_context":"1914년 페미니스트 운동가 메리 리처드슨이 작품에 도끼질을 했으며 이후 완벽히 복원되었습니다.","visual_connection":"거울 속 흐릿하게 반영된 비너스의 얼굴이 관람자를 바라보는 구성은 보는 자와 보이는 자의 관계를 역전시키는 교묘한 장치입니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_ghent_altarpiece","title":"The Ghent Altarpiece","title_aliases":["ghent altarpiece","겐트","제단화","het lam gods"],"artist":"Jan van Eyck","art_movement":"플랑드르 회화","creation_period":"1432년 완성. 벨기에 겐트 성 바보 대성당 소장. 반 에이크 형제가 착수하고 얀이 완성한 12폭 제단화입니다.","historical_context":"15세기 초 플랑드르는 북유럽 무역의 중심지로 부유한 시민 계층이 종교 예술을 후원했습니다.","artist_context":"얀 반 에이크는 유화 기법을 완성한 화가로 알려져 있습니다. 미세한 세부 묘사와 빛의 표현이 당대 혁명적이었습니다.","visual_connection":"열두 폭 제단화를 펼치면 천국의 어린 양을 경배하는 성인들이 장대한 풍경 속에 펼쳐집니다. 각 패널의 인물·식물·직물을 극도의 정밀함으로 묘사했습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"hunters_in_the_snow_bruegel","title":"Hunters in the Snow","title_aliases":["hunters in the snow","눈 속 사냥꾼","jäger im schnee"],"artist":"Pieter Bruegel the Elder","art_movement":"북방 르네상스","creation_period":"1565년 제작. 빈 미술사박물관 소장. 12개월 연작 중 1월을 묘사한 작품입니다.","historical_context":"16세기 중반 유럽은 소빙기로 겨울이 유난히 혹독했습니다. 브뤼헐은 농민들의 일상 풍경을 통해 자연과 인간의 관계를 탐구했습니다.","artist_context":"브뤼헐은 농민 화가라는 별명답게 귀족보다 평범한 사람들의 삶을 즐겨 그렸습니다.","visual_connection":"사냥을 마치고 집으로 돌아오는 사냥꾼들의 실루엣, 눈 덮인 마을, 얼어붙은 연못에서 스케이트 타는 사람들이 겨울 풍경의 서정적 파노라마를 이룹니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_tower_of_babel","title":"The Tower of Babel","title_aliases":["tower of babel","바벨탑","turmbau zu babel"],"artist":"Pieter Bruegel the Elder","art_movement":"북방 르네상스","creation_period":"1563년 제작. 빈 미술사박물관 소장.","historical_context":"성경 창세기의 바벨탑 이야기는 인간의 오만과 신의 응징으로 읽힙니다. 16세기 종교 분쟁 속에서 인간 야망에 대한 경고로 해석되기도 했습니다.","artist_context":"브뤼헐은 로마 콜로세움을 참고해 구체적이고 사실적인 건축물을 묘사했습니다. 수백 명의 인물이 건설 작업에 종사하는 세밀한 풍속화이기도 합니다.","visual_connection":"하늘을 향해 솟아오르는 거대한 탑이 이미 무너지기 시작한 징후를 보이며, 그 규모에 비해 인물들이 개미처럼 작게 묘사되어 인간 야망의 허망함을 강조합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"wanderer_above_the_sea_of_fog","title":"Wanderer above the Sea of Fog","title_aliases":["wanderer","안개바다","방랑자","der wanderer","sea of fog"],"artist":"Caspar David Friedrich","art_movement":"낭만주의","creation_period":"1818년경 제작. 함부르크 미술관 소장.","historical_context":"19세기 초 독일 낭만주의는 자연 앞에서 인간의 숭고한 감정을 탐구했습니다. 나폴레옹 전쟁 이후 독일 민족주의와 개인의 자유에 대한 갈망이 결합되었습니다.","artist_context":"프리드리히는 자연 앞에 선 고독한 인물을 반복해 그리며 인간과 무한한 자연의 대립을 표현했습니다.","visual_connection":"안개 바다 위 절벽에 혼자 서서 끝없는 풍경을 바라보는 인물의 뒷모습은 관람자 자신을 그 위치에 투사하게 만들며 숭고와 고독을 동시에 느끼게 합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_monk_by_the_sea","title":"The Monk by the Sea","title_aliases":["monk by the sea","수도사","der mönch am meer"],"artist":"Caspar David Friedrich","art_movement":"낭만주의","creation_period":"1808~1810년 제작. 베를린 구 국립미술관 소장.","historical_context":"19세기 초 낭만주의 화가들은 광대한 자연 앞에서 인간의 미소함을 탐구했습니다.","artist_context":"프리드리히는 이 작품에서 인물을 극단적으로 작게 그려 자연의 광대함을 강조했습니다. 독일의 시인 클라이스트가 이 작품 앞에서 압도적 감동을 기록했습니다.","visual_connection":"화면의 90% 이상이 하늘과 바다로 채워진 가운데 수평선 근처의 작은 수도사 실루엣이 무한함 앞에 선 고독한 인간을 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_fighting_temeraire","title":"The Fighting Temeraire","title_aliases":["fighting temeraire","테메레르","temeraire"],"artist":"J. M. W. Turner","art_movement":"낭만주의","creation_period":"1839년 제작. 런던 내셔널객러리 소장. 영국인들이 가장 좋아하는 그림 설문에서 수차례 1위를 차지했습니다.","historical_context":"증기선이 범선을 대체하던 산업혁명 시기, 트라팔가르 해전의 영웅함 테메레르호가 증기 예인선에 이끌려 해체장으로 가는 장면입니다.","artist_context":"터너는 빛과 대기의 효과를 극단적으로 추구했습니다. 이 작품에서 석양의 황금빛은 과거 영광의 소멸과 새 시대의 도래를 동시에 표현합니다.","visual_connection":"석양의 붉은 빛 속에서 유령처럼 흰 테메레르호와 시커먼 연기를 내뿜는 증기 예인선의 대비가 과거와 미래, 아름다움과 산업화의 긴장을 드라마틱하게 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"rain_steam_and_speed","title":"Rain, Steam and Speed","title_aliases":["rain steam speed","비 증기 속도"],"artist":"J. M. W. Turner","art_movement":"낭만주의","creation_period":"1844년 제작. 런던 내셔널갤러리 소장. 증기 기관차를 그린 초기 회화 중 하나입니다.","historical_context":"철도 혁명이 영국 사회를 바꾸던 1840년대, 기차는 속도와 현대성의 상징이었습니다.","artist_context":"터너는 런던에서 브리스톨로 가는 그레이트 웨스턴 철도를 묘사했습니다. 폭풍 속 달리는 기차를 거의 추상에 가깝게 표현했습니다.","visual_connection":"비·안개·증기가 뒤섞인 황금빛 대기 속에서 기관차가 돌진하는 장면은 속도와 자연 앞에서 느끼는 숭고함을 포착합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_hay_wain","title":"The Hay Wain","title_aliases":["hay wain","건초수레","haywain"],"artist":"John Constable","art_movement":"낭만주의","creation_period":"1821년 제작. 런던 내셔널갤러리 소장. 영국 미술의 아이콘으로 꼽히는 전원 풍경화입니다.","historical_context":"산업혁명으로 영국 농촌이 변화하던 시기, 컨스터블은 사라져가는 전통 풍경을 기록했습니다.","artist_context":"컨스터블은 구름과 빛의 순간적 변화를 포착하기 위해 야외에서 스케치하는 방식을 개척했습니다. 프랑스 들라크루아에게 큰 영향을 미쳤습니다.","visual_connection":"건초 수레가 강을 건너는 평화로운 오후, 움직이는 구름 아래 초록빛 풀밭과 물의 반영이 영국 전원의 서정을 완벽하게 담아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_cradle","title":"The Cradle","title_aliases":["the cradle","요람","le berceau"],"artist":"Berthe Morisot","art_movement":"인상주의","creation_period":"1872년 제작. 파리 오르세 미술관 소장. 모리조의 여동생 에드마가 아기를 돌보는 장면입니다.","historical_context":"19세기 후반 프랑스 인상주의 운동에서 여성 화가들은 주로 가정 내 일상을 주제로 그렸습니다. 공공장소 접근이 제한되었기 때문입니다.","artist_context":"모리조는 마네의 영향을 받아 인상주의 기법을 발전시켰으며, 마네의 동생과 결혼했습니다. 여성 일상의 내밀한 순간을 섬세하게 포착했습니다.","visual_connection":"얇은 베일로 가려진 아기 침대를 내려다보는 어머니의 시선이 부드러운 필촉과 함께 모성의 따뜻함을 자연스럽게 전달합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_child_bath","title":"The Child's Bath","title_aliases":["child's bath","아이 목욕","목욕하는 아이","la toilette"],"artist":"Mary Cassatt","art_movement":"인상주의","creation_period":"1893년 제작. 시카고 아트 인스티튜트 소장.","historical_context":"19세기 말 미국 출신으로 파리에서 활동한 카사트는 여성과 아이의 일상을 주제로 삼았습니다.","artist_context":"카사트는 드가의 초청으로 인상주의 그룹에 합류한 유일한 미국인이었습니다. 일본 판화의 영향을 받아 대담한 윤곽선과 평면적 색채를 사용했습니다.","visual_connection":"위에서 내려다보는 시점과 아이를 목욕시키는 여성의 집중된 시선이 일상의 소소한 돌봄을 따뜻하게 포착합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"praying_hands","title":"Praying Hands","title_aliases":["praying hands","기도하는 손","betende hände"],"artist":"Albrecht Dürer","art_movement":"북방 르네상스","creation_period":"1508년 제작. 빈 알베르티나 미술관 소장. 헬러 제단화를 위한 습작으로 그려졌습니다.","historical_context":"16세기 초 독일 종교개혁 전야, 가톨릭 신앙과 인문주의가 공존하던 시기입니다.","artist_context":"뒤러는 이탈리아 르네상스를 북유럽에 전파하는 역할을 했습니다. 정밀한 관찰과 묘사력으로 자연물과 인체를 탁월하게 재현했습니다.","visual_connection":"앙상하고 마디진 손이 경건하게 모아진 모습은 몇 백 년이 지난 지금도 기도와 신앙의 보편적 아이콘으로 남아 있습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"self_portrait_at_28","title":"Self-Portrait at 28","title_aliases":["self portrait 28","자화상","selbstbildnis"],"artist":"Albrecht Dürer","art_movement":"북방 르네상스","creation_period":"1500년 제작. 뮌헨 알테 피나코테크 소장. 정면을 응시하는 거의 유일한 르네상스 자화상입니다.","historical_context":"당시 정면 초상화는 예수 그리스도에게만 허용된 구도였습니다. 뒤러가 이 형식을 선택한 것은 예술가의 신적 창조력을 주장하는 의미였습니다.","artist_context":"뒤러는 자화상을 통해 예술가의 사회적 지위 향상을 꾀했습니다. 르네상스 이상형인 우아한 외모와 자의식을 표현했습니다.","visual_connection":"정면을 응시하는 자신감 있는 눈빛, 정교하게 묘사된 곱슬머리, 모피 코트가 예술가로서의 자부심을 선언합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"plum_garden_kameido","title":"Plum Garden at Kameido","title_aliases":["plum garden","매화원","kameido","梅屋鋪"],"artist":"Utagawa Hiroshige","art_movement":"우키요에","creation_period":"1857년, 히로시게의 에도 100경 연작 중 하나.","historical_context":"에도 후기 일본의 목판화는 서민 문화의 꽃이었습니다. 매화는 봄의 도래를 알리는 일본 문화의 상징입니다.","artist_context":"히로시게는 풍경화로 일본 우키요에를 완성시켰습니다. 이 작품은 반 고흐가 직접 유화로 모사할 만큼 서양 화가들에게 큰 영향을 미쳤습니다.","visual_connection":"굵은 매화 가지가 화면 전체를 가로지르는 대담한 구도는 일본 미술 특유의 장식적 평면성을 보여주며, 강 건너 소박한 전경과의 대비가 아름답습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"sudden_shower_shin_ohashi","title":"Sudden Shower over Shin-Ohashi","title_aliases":["sudden shower","소나기","ohashi","大橋","rain"],"artist":"Utagawa Hiroshige","art_movement":"우키요에","creation_period":"1857년, 에도 100경 연작 중 하나. 반 고흐가 유화로 모사한 작품입니다.","historical_context":"에도 막부 말기 일본의 일상과 자연 풍경을 담은 연작으로 당시 도시민의 삶을 기록합니다.","artist_context":"히로시게는 빗줄기를 가는 수직선으로 표현하는 독창적 방식을 개발했습니다. 이 기법은 이후 인상주의 화가들에게 큰 영향을 미쳤습니다.","visual_connection":"세차게 쏟아지는 빗줄기 속에서 다리를 급히 건너는 사람들의 실루엣이 운동감과 긴장감을 만들어냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_lady_of_shalott","title":"The Lady of Shalott","title_aliases":["lady of shalott","샬롯","shalott"],"artist":"John William Waterhouse","art_movement":"라파엘전파","creation_period":"1888년 제작. 런던 테이트 갤러리 소장. 테니슨의 동명 시에서 영감을 받았습니다.","historical_context":"19세기 중후반 영국 라파엘전파는 중세 문학과 전설에서 주제를 가져와 이상화된 여성 이미지를 그렸습니다.","artist_context":"워터하우스는 라파엘전파의 영향을 받아 신화와 문학 속 여성을 즐겨 그렸습니다. 아름답지만 비극적인 여성 인물을 반복해 표현했습니다.","visual_connection":"거울을 통해서만 세상을 보던 저주를 어기고 창문 밖으로 캐멀롯을 바라보다 죽음에 이르는 여인이 촛불이 꺼지는 보트 위에 앉아 있습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"ophelia_millais","title":"Ophelia","title_aliases":["millais ophelia","오필리아 밀레이","ophelia millais"],"artist":"John Everett Millais","art_movement":"라파엘전파","creation_period":"1851~1852년 제작. 런던 테이트 갤러리 소장. 셰익스피어의 햄릿에서 오필리아가 물에 빠져 죽는 장면을 묘사했습니다.","historical_context":"19세기 중반 영국 라파엘전파는 자연의 정밀한 묘사와 중세 문학 주제를 결합했습니다.","artist_context":"밀레이는 배경 식물들을 수개월간 야외에서 직접 관찰해 그렸습니다. 모델 엘리자베스 시달이 차가운 목욕통에서 포즈를 취하다 폐렴에 걸렸습니다.","visual_connection":"물 위에 떠 있는 오필리아가 꽃을 손에 쥔 채 고요하게 눈을 감은 모습은 죽음과 아름다움, 광기와 순수를 동시에 담아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_annunciation","title":"The Annunciation","title_aliases":["annunciation","수태고지","annunciazione"],"artist":"Fra Angelico","art_movement":"르네상스 초기","creation_period":"1438~1450년경 제작. 피렌체 산마르코 수도원 프레스코화. 수도사들의 명상을 위한 종교 이미지였습니다.","historical_context":"15세기 피렌체에서 인문주의와 기독교 신앙이 융합되던 시기, 프라 안젤리코는 수도사이자 화가로 두 세계를 통합했습니다.","artist_context":"프라 안젤리코는 평생 수도사로 살면서 그림을 그렸습니다. 그의 작품들은 기도하는 마음으로 그린 것이라고 알려져 있습니다.","visual_connection":"천사 가브리엘과 성모 마리아가 우아한 아치 아래 마주 앉은 장면은 금빛 배경 없이 현실적 공간감을 구현한 초기 르네상스의 혁신을 보여줍니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"lamentation_of_christ","title":"Lamentation of Christ","title_aliases":["lamentation of christ","그리스도 애도","compianto sul cristo morto"],"artist":"Giotto di Bondone","art_movement":"중세 / 르네상스 선구","creation_period":"1304~1306년 제작. 이탈리아 파도바 스크로베니 예배당 프레스코화.","historical_context":"13~14세기 이탈리아에서 비잔틴 양식을 넘어 자연주의적 표현으로 이행하는 전환기였습니다.","artist_context":"조토는 인물에 실재감과 감정을 부여하는 방식으로 서양 미술사의 혁명을 일으켰습니다. 단테는 그를 가장 위대한 화가라 칭했습니다.","visual_connection":"죽은 예수를 중심으로 주위 인물들이 실제 감정을 표현하며 슬퍼하는 장면은 비잔틴의 경직된 양식을 벗어나 인간적 드라마를 구현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"narcissus_caravaggio","title":"Narcissus","title_aliases":["narcissus","나르키소스","narciso"],"artist":"Caravaggio","art_movement":"바로크","creation_period":"1597~1599년경 제작. 로마 국립고대미술관 소장.","historical_context":"그리스 신화에서 나르키소스는 물에 비친 자신의 모습에 반해 죽은 인물입니다. 카라바조 시대에도 자기 도취와 허영에 대한 도덕적 경고로 읽혔습니다.","artist_context":"카라바조는 키아로스쿠로 기법으로 강렬한 명암 대비를 만들었습니다. 이 작품은 그의 귀속이 논란이 되기도 했습니다.","visual_connection":"수면에 완벽하게 반영된 소년의 모습이 실제와 반영 사이의 경계를 모호하게 만듭니다. 어두운 배경과 빛 받은 인물의 극적 대비가 이야기의 비극성을 강조합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"i_and_the_village","title":"I and the Village","title_aliases":["i and the village","나와마을","moi et le village"],"artist":"Marc Chagall","art_movement":"초현실주의 / 입체주의","creation_period":"1911년 파리에서 제작. 뉴욕 현대미술관(MoMA) 소장.","historical_context":"20세기 초 파리는 입체주의·야수주의 등 아방가르드 운동의 중심지였습니다. 러시아 출신 샤갈은 고향 비테프스크의 기억을 현대 미술 언어로 표현했습니다.","artist_context":"샤갈은 꿈과 기억, 동화적 상상력을 회화에 결합시켰습니다. 유대 민족 문화와 러시아 농촌 생활이 작품의 중요한 원천입니다.","visual_connection":"사람과 동물이 같은 눈높이에서 마주 보는 구도, 거꾸로 된 집들, 공중에 떠 있는 인물들이 꿈의 논리로 조합되어 고향의 기억을 환상적으로 재구성합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_son_of_man_magritte","title":"The Son of Man","title_aliases":["son of man","인간의아들","le fils de l'homme"],"artist":"René Magritte","art_movement":"초현실주의","creation_period":"1964년 제작. 마그리트 자신의 자화상입니다.","historical_context":"20세기 중반 초현실주의는 일상적 사물의 낯선 조합으로 무의식의 논리를 탐구했습니다.","artist_context":"마그리트는 녹색 사과가 얼굴을 가리는 이유에 대해 보이는 것과 숨겨진 것 사이의 갈등을 탐구하기 위해서라고 설명했습니다.","visual_connection":"정장을 입고 멜론 모자를 쓴 남성의 얼굴을 녹색 사과가 가립니다. 보이지 않는 것에 대한 호기심, 일상과 이상함의 공존이 이 단순한 구성 안에 모두 담겨 있습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_sleeping_gypsy","title":"The Sleeping Gypsy","title_aliases":["sleeping gypsy","잠자는집시","la bohémienne endormie"],"artist":"Henri Rousseau","art_movement":"나이브 아트 / 원시주의","creation_period":"1897년 제작. 뉴욕 현대미술관(MoMA) 소장.","historical_context":"19세기 말 파리에서 아카데미 교육을 받지 않은 루소는 독학으로 독특한 화풍을 발전시켰습니다.","artist_context":"루소는 세관원으로 일하며 독학으로 그림을 그려 세관원 루소라 불렸습니다. 아프리카·정글 풍경은 상상으로 그린 것이었지만 놀라운 설득력을 가집니다.","visual_connection":"달빛 아래 잠든 집시 옆에 사자가 다가와 냄새를 맡는 장면이 신비롭고 고요하게 표현됩니다. 위험과 평화가 공존하는 꿈 같은 분위기가 인상적입니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"madame_x","title":"Madame X","title_aliases":["madame x","마담x","madame gautreau"],"artist":"John Singer Sargent","art_movement":"인상주의 / 아카데미즘","creation_period":"1884년 제작. 뉴욕 메트로폴리탄 미술관 소장. 파리 살롱에서 스캔들을 일으켜 사전트가 미국으로 귀국하는 계기가 되었습니다.","historical_context":"19세기 말 파리 사교계에서 아름다운 여성의 초상화는 사회적 명성을 좌우했습니다.","artist_context":"사전트는 아메리카계 파리 사교계 여성 버지니 고트로를 모델로 했습니다. 원작에서 어깨끈이 내려와 있어 스캔들이 되었고 나중에 수정했습니다.","visual_connection":"자신감 있게 몸을 돌린 자세, 창백한 피부와 검은 드레스의 강렬한 대비, 황금빛 테이블과 배경이 우아하면서도 도전적인 분위기를 자아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"a_bigger_splash","title":"A Bigger Splash","title_aliases":["bigger splash","물보라","splash"],"artist":"David Hockney","art_movement":"팝 아트 / 네오리얼리즘","creation_period":"1967년 제작. 런던 테이트 갤러리 소장. 로스앤젤레스 이주 후 캘리포니아의 햇빛과 수영장에 매료되어 제작한 연작 중 하나입니다.","historical_context":"1960년대 미국 캘리포니아는 낙관주의와 소비 문화의 상징이었습니다. 호크니는 영국인의 눈으로 이 새로운 세계를 포착했습니다.","artist_context":"호크니는 다이빙 직후 물보라만 남기고 인물이 사라진 순간을 포착했습니다. 수영장 연작은 그의 대표 시리즈입니다.","visual_connection":"평화로운 파란 하늘·수영장과 격렬한 하얀 물보라의 대비가 드라마틱한 순간을 포착합니다. 방금 누군가 다이빙했다는 흔적만 남은 화면이 관람자의 상상력을 자극합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"beata_beatrix","title":"Beata Beatrix","title_aliases":["beata beatrix","베아트리체","blessed beatrice"],"artist":"Dante Gabriel Rossetti","art_movement":"라파엘전파","creation_period":"1864~1870년 제작. 런던 테이트 갤러리 소장. 단테의 신곡 속 베아트리체를 통해 1862년 사망한 아내 엘리자베스 시달을 추모했습니다.","historical_context":"19세기 중반 영국 라파엘전파는 중세와 이탈리아 르네상스에서 영감을 받아 강렬한 색채와 감성적 내용을 추구했습니다.","artist_context":"로세티의 아내 시달은 약물 과다 복용으로 사망했습니다. 이 작품은 단테의 베아트리체와 아내를 동일시하며 그린 애도의 기록입니다.","visual_connection":"붉은 새가 양귀비(아편의 상징)를 전달하는 황홀경 속의 여인 얼굴이 황금빛 안개 속에 표현되어 죽음과 환상이 경계를 이룹니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"la_grande_odalisque","title":"La Grande Odalisque","title_aliases":["grande odalisque","오달리스크","odalisque"],"artist":"Jean-Auguste-Dominique Ingres","art_movement":"신고전주의","creation_period":"1814년 제작. 파리 루브르 박물관 소장. 나폴레옹의 여동생 카롤린 뮈라의 의뢰로 제작했습니다.","historical_context":"19세기 초 나폴레옹 이집트 원정 이후 오리엔탈리즘이 유행했습니다. 터키 하렘의 여성들이 이국적 주제로 각광받았습니다.","artist_context":"앵그르는 살롱에서 이 작품을 출품했으나 해부학적으로 부정확하다는 비판을 받았습니다. 척추가 실제보다 3~4개 더 많습니다.","visual_connection":"뒤를 돌아보는 우아한 시선, 길게 늘어진 등, 공작 부채와 향로 연기 등 이국적 소품이 관능적이면서도 고전적인 이상미를 구현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"nymphs_and_satyr","title":"Nymphs and Satyr","title_aliases":["nymphs satyr","님프","nymphes et satyre"],"artist":"William-Adolphe Bouguereau","art_movement":"아카데미즘","creation_period":"1873년 제작. 매사추세츠 클라크 미술관 소장.","historical_context":"19세기 후반 프랑스 아카데미즘은 고전 신화를 소재로 한 이상화된 인체 표현을 최고 예술로 여겼습니다.","artist_context":"부게로는 살롱의 총아로 당대 가장 성공한 화가였지만, 인상주의자들에게는 보수주의의 상징으로 비판받았습니다.","visual_connection":"네 님프가 사티로스를 물속으로 끌어들이려는 장면을 부드러운 색채와 완벽한 인체 묘사로 표현했습니다. 고전 조각 같은 매끄러운 인체와 목가적 풍경이 조화롭습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"et_in_arcadia_ego","title":"Et in Arcadia Ego","title_aliases":["et in arcadia ego","arcadia","아르카디아","les bergers"],"artist":"Nicolas Poussin","art_movement":"바로크 / 고전주의","creation_period":"1637~1638년경 제작. 파리 루브르 박물관 소장.","historical_context":"17세기 프랑스 고전주의는 고대 그리스·로마의 이성과 질서를 이상으로 삼았습니다. 아르카디아는 이상적 전원 낙원의 상징입니다.","artist_context":"푸생은 프랑스 출신이지만 평생 로마에 거주하며 고대 문화를 연구했습니다. 그의 작품은 이성적 구성과 철학적 내용으로 유명합니다.","visual_connection":"목동들이 묘비에 나도 아르카디아에 있었다라는 문구를 읽는 장면은 이상적 낙원에도 죽음이 존재한다는 메멘토 모리의 주제를 차분하게 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_melancholy","title":"Melancholy","title_aliases":["melancholy","우울","melankoli","yellow boat"],"artist":"Edvard Munch","art_movement":"표현주의 / 상징주의","creation_period":"1894~1895년 제작. 오슬로 뭉크 미술관 소장.","historical_context":"19세기 말 유럽에서 개인의 심리적 고통을 예술로 표현하는 움직임이 강해졌습니다.","artist_context":"뭉크는 실연과 친구의 불행한 사랑을 목격하며 이 작품을 그렸습니다. 해변에 홀로 앉은 인물은 그의 시리즈 생의 프리즈에 속합니다.","visual_connection":"해변에 홀로 웅크린 인물, 일렁이는 해변선, 멀리 떠가는 보트가 내면의 고독과 단절감을 표현합니다. 물결치는 선들이 불안한 감정 상태를 시각화합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"lavender_mist","title":"Lavender Mist: Number 1","title_aliases":["lavender mist","라벤더","lavender fog"],"artist":"Jackson Pollock","art_movement":"추상 표현주의","creation_period":"1950년 제작. 워싱턴 국립미술관 소장.","historical_context":"2차 세계대전 후 미국 추상 표현주의는 유럽 중심의 미술사를 미국으로 전환시켰습니다.","artist_context":"폴록의 드리핑 연작 중 가장 서정적인 작품으로 꼽힙니다. 평론가 클레멘트 그린버그가 제목을 붙였습니다.","visual_connection":"라벤더·은회색·흰색 등 부드러운 색조의 물감이 얽혀 안개처럼 퍼져나가며, 규칙과 우연이 공존하는 화면이 시각적 명상을 유도합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"no_61_rust_and_blue","title":"No. 61 (Rust and Blue)","title_aliases":["no 61","rust and blue","녹과 파랑","로스코"],"artist":"Mark Rothko","art_movement":"추상 표현주의 / 색면 회화","creation_period":"1953년 제작. 로스코의 색면 회화 시기 대표작.","historical_context":"1950년대 미국에서 추상 표현주의는 전후 실존주의 철학과 결합해 감정의 직접 전달을 추구했습니다.","artist_context":"로스코는 색면 회화를 통해 관람자가 그림 앞에서 초월적 감동을 경험하기를 원했습니다. 그림과 나란히 서는 것이 아니라 그림 속으로 들어가는 경험을 추구했습니다.","visual_connection":"두 개의 색 덩어리가 모호한 경계로 겹치며 화면을 채웁니다. 가까이 다가설수록 색채가 진동하듯 느껴지며 감정 직접 전달의 효과가 극대화됩니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"orange_and_yellow","title":"Orange and Yellow","title_aliases":["orange yellow","오렌지 노랑","color field"],"artist":"Mark Rothko","art_movement":"색면 회화","creation_period":"1956년 제작. 로스코의 가장 밝고 따뜻한 색면 시기 작품입니다.","historical_context":"1950년대 미국에서 추상 미술이 주류로 자리잡으면서 색채 자체의 감정적 효과에 대한 탐구가 활발해졌습니다.","artist_context":"로스코는 자신의 그림이 단순한 추상이 아니라 비극·황홀·운명을 표현한다고 강조했습니다.","visual_connection":"따뜻한 오렌지와 노란색이 부드럽게 진동하며 화면을 채우는 이 작품은 로스코 특유의 명상적이고 감정적인 공간을 만들어냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"black_iris","title":"Black Iris","title_aliases":["black iris","검은 붓꽃","검은 아이리스"],"artist":"Georgia O'Keeffe","art_movement":"아메리칸 모더니즘","creation_period":"1926년 제작. 뉴욕 메트로폴리탄 미술관 소장.","historical_context":"1920년대 뉴욕은 현대 미술의 새로운 중심지로 부상했습니다. 오키프는 꽃을 클로즈업해 추상에 가깝게 표현하는 독특한 방식을 개발했습니다.","artist_context":"오키프는 꽃을 매우 크게 그려 사람들이 바쁜 일상에서 멈추고 꽃을 바라보게 만들고 싶었다고 말했습니다.","visual_connection":"깊고 어두운 검은 보라색 꽃잎이 화면을 가득 채우며, 꽃의 중심부로 빨려들어가는 듯한 감각을 줍니다. 추상과 구상의 경계에서 시각적 황홀감을 자아냅니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_birthday","title":"The Birthday","title_aliases":["birthday","생일","l'anniversaire"],"artist":"Marc Chagall","art_movement":"초현실주의","creation_period":"1915년 제작. 뉴욕 현대미술관(MoMA) 소장. 아내 벨라가 생일 꽃다발을 들고 온 날을 그렸습니다.","historical_context":"러시아 혁명 직전의 격변기에 샤갈은 개인적 행복의 순간을 공중 부양으로 표현했습니다.","artist_context":"샤갈은 사랑하는 사람과 함께할 때의 행복감이 공중에 뜨는 기분이라고 표현했습니다. 그의 작품에서 공중 부양은 기쁨과 사랑의 상징입니다.","visual_connection":"꽃다발을 든 여인과 공중에 뜬 남성이 키스하는 장면이 작은 방 안에서 펼쳐집니다. 중력을 거스르는 사랑의 기쁨을 그대로 시각화했습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_empire_of_light","title":"The Empire of Light","title_aliases":["empire of light","빛의제국","l empire des lumieres"],"artist":"René Magritte","art_movement":"초현실주의","creation_period":"1953~1954년 제작. 브뤼셀 왕립미술관 소장.","historical_context":"20세기 중반 초현실주의는 일상의 논리를 뒤흔드는 방식으로 현실 인식에 도전했습니다.","artist_context":"마그리트는 이 구성을 워낙 좋아해 같은 주제로 17점을 그렸습니다.","visual_connection":"낮의 하늘과 밤의 거리가 한 화면에 공존하는 이 작품은 우리가 당연하게 여기는 시간의 질서를 뒤흔들며 현실과 꿈의 경계를 묻습니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_third_of_may","title":"The Third of May 1808","title_aliases":["third of may","5월 3일","처형","el tres de mayo"],"artist":"Francisco Goya","art_movement":"낭만주의","creation_period":"1814년 제작. 마드리드 프라도 미술관 소장. 나폴레옹 군대에 저항하다 처형당한 마드리드 시민들을 추모했습니다.","historical_context":"1808년 5월 2일 마드리드 시민들이 프랑스 군대에 봉기했고, 다음날 수백 명이 처형되었습니다. 스페인 독립 전쟁의 시작이었습니다.","artist_context":"고야는 이 작품으로 전쟁의 공포와 권력의 잔인성을 고발했습니다. 현대 전쟁화의 원형으로 피카소의 게르니카에 직접적 영향을 미쳤습니다.","visual_connection":"두 팔을 벌려 십자가처럼 처형을 기다리는 하얀 셔츠의 남성과 얼굴 없는 총병들의 대비가 희생자의 인간성과 가해자의 비인간성을 극적으로 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"saturn_devouring_his_son","title":"Saturn Devouring His Son","title_aliases":["saturn devouring","사투르누스","saturn","saturno devorando"],"artist":"Francisco Goya","art_movement":"낭만주의 / 검은 그림","creation_period":"1820~1823년, 고야의 검은 그림 연작 중 하나로 그의 별장 벽에 직접 그린 프레스코화였습니다.","historical_context":"나폴레옹 전쟁과 스페인 정치 혼란으로 말년의 고야는 인간의 잔인성과 권력에 대한 극도의 절망을 표현했습니다.","artist_context":"귀머거리가 된 고야가 만년의 고독 속에서 자신의 집 벽에 그린 14점의 검은 그림 중 하나입니다. 공개를 위한 작품이 아닌 지극히 사적인 표현입니다.","visual_connection":"어둠 속에서 거대한 손으로 자식을 삼키는 사투르누스의 광기 어린 눈이 권력과 두려움, 노쇠에 대한 원초적 공포를 직접적으로 표현합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_night_watch","title":"The Night Watch","title_aliases":["night watch","de nachtwacht","야경대","야경꾼"],"artist":"Rembrandt van Rijn","art_movement":"바로크 / 네덜란드 황금시대","creation_period":"1642년 제작. 암스테르담 국립미술관 소장. 원제는 프란스 반닝 코크 대장의 민병대입니다.","historical_context":"17세기 암스테르담은 세계 무역의 중심지로 번영을 누렸습니다. 민병대 단체 초상화는 당시 네덜란드의 독특한 예술 장르였습니다.","artist_context":"렘브란트는 전통적인 단체 초상화 형식을 깨고 역동적인 행군 장면을 연출했습니다. 이 작품 이후 의뢰가 줄어 경제적 어려움을 겪었습니다.","visual_connection":"빛과 그림자의 극적 대비 속에서 다양한 민병대원들이 움직이는 역동적 구성은 단체 초상화를 역사화 수준의 드라마로 끌어올렸습니다. 화면 중앙의 밝은 소녀가 신비로운 분위기를 더합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"las_meninas","title":"Las Meninas","title_aliases":["las meninas","시녀들","라스 메니나스"],"artist":"Diego Velázquez","art_movement":"바로크","creation_period":"1656년 제작. 마드리드 프라도 미술관 소장. 서양 미술사에서 가장 많이 분석된 작품 중 하나입니다.","historical_context":"17세기 스페인 합스부르크 왕조 필리페 4세의 궁정을 배경으로 합니다.","artist_context":"벨라스케스는 자신을 그림 속에 등장시켜 화가의 지위와 예술의 본질에 대한 질문을 던집니다.","visual_connection":"캔버스 앞에 선 화가, 공주와 시녀들, 거울 속 왕 부부의 반영이 복잡한 공간과 시선의 교차를 만들어냅니다. 보는 자와 보이는 자, 현실과 표현의 경계가 허물어집니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"guernica_picasso","title":"Guernica","title_aliases":["게르니카","guernica"],"artist":"Pablo Picasso","art_movement":"입체주의","creation_period":"1937년, 스페인 내전 중 게르니카 폭격에 분노해 6주 만에 완성. 마드리드 소피아 왕비 국립미술관 소장.","historical_context":"1937년 4월 26일 나치 독일 콘도르 군단이 바스크 지방 소도시 게르니카를 무차별 폭격해 수백 명이 사망했습니다.","artist_context":"피카소는 프랑코 독재 동안 이 작품의 스페인 반입을 거부했습니다. 민주주의가 회복되면 돌려보내라는 유언대로 1981년 스페인으로 반환되었습니다.","visual_connection":"흑백의 단색 화면에 비명 지르는 말, 죽은 아이를 안은 어머니, 타오르는 불꽃이 입체주의 파편으로 충돌하며 전쟁의 공포를 시각적 충격으로 전달합니다.","confidence":"verified","sources":["curated_db"]},
  {"artwork_id":"the_kiss_klimt","title":"The Kiss","title_aliases":["the kiss","키스","der kuss","황금의 키스"],"artist":"Gustav Klimt","art_movement":"상징주의 / 아르누보","creation_period":"1907~1908년 제작. 빈 벨베데레 미술관 소장. 클림트 황금 시기의 정점입니다.","historical_context":"20세기 초 빈은 프로이트의 정신분석학, 말러의 음악이 공존하는 문화 중심지였습니다.","artist_context":"클림트는 금박을 직접 붙이는 기법으로 비잔틴 모자이크에서 영감받은 기하학적 문양을 구현했습니다.","visual_connection":"금빛 문양으로 뒤덮인 두 연인의 포옹에서 남성의 사각형 문양과 여성의 원형·꽃 문양의 대비가 남성성과 여성성의 조화를 장식 언어로 표현합니다.","confidence":"verified","sources":["curated_db"]},
]

added = 0
for e in NEW:
    if e["artwork_id"] not in existing:
        db["artworks"].append(e)
        existing.add(e["artwork_id"])
        added += 1
        print(f"Added: {e['artwork_id']}")
    else:
        print(f"Skip: {e['artwork_id']}")

DB_PATH.write_text(json.dumps(db, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"\nDone. Added {added}. Total: {len(db['artworks'])}")
